### ISSUE TITLE
Add O.Krok. II metadata

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#101]
Add O.Krok. II (o.krok;2;) metadata to
http://aquila.zaw.uni-heidelberg.de/
and
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc

**Comment by jcowey** [comment]
https://docs.google.com/spreadsheets/d/1ICVCgJ7oBWzZqOf2QOjR02hRMNUNw3dZN7WlOfsEWZY/edit#gid=0

**Comment by jcowey** [comment]
You will find the fmp12 file in
252/Admin/hgv/oKrok2/...
The file is:
transfer_oKrok2_Carmen.fmp12

Would you please xwalk these to EpiDoc and then create a pull request so that I can check them and then merge to master.

Would you also please add the records to our FilMaker master file and then push that to aquilaHGV.

Almost all NEW records. There are 3 MODIFIED records.

**Comment by jcowey** [comment]
Special request:
Would you please look at columns S, T, U in the tab `4papyriDotInfoEntryReady`

Would it be possible for you to read the contents of these columns into the relevant elements.

This is something you do not usually do.

We can chat about it tomorrow

**Comment by jcowey** [comment]
Here is the pull request with the details:
https://github.com/papyri/idp.data/pull/144

Now successfully merged. Everything displaying as required.

**Comment by jcowey** [comment]
Make relevant changes to hgv.texte

**Comment by jcowey** [comment]
I have made changes to Liste.html
https://github.com/Edelweiss/hgv.texte/commit/75c35da277791dfe309ae7b8c1d1bb7c07291229
and
SB/SB_XXVIII.html (redirects)
https://github.com/Edelweiss/hgv.texte/commit/e63c92424d2782aa9ab701b60b128cc435e47b75

**Comment by Edelweiss** [comment]
Okay…

https://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html

**Comment by Edelweiss** [comment]
Übrigens…

![Bildschirmfoto 2020-05-14 um 13 44 40](https://user-images.githubusercontent.com/612862/81930671-322dc380-95e9-11ea-8686-8af185ac089f.png)

Das Laden der Bilder im iframe wird immer unbeliebter. Einerseits gibt es das http/https-Problem und nun auch noch das.

**Comment by Edelweiss** [comment]
Außerdem können folgende beiden Dateien wahrscheinlich gelöscht werden, oder?

- P.Lond. IV.txt
- P.Lond. V.txt

Siehe hier https://github.com/Edelweiss/hgv.texte/tree/master/P.Lond.

**Comment by Edelweiss** [comment]
Diese Art Unicode-Probleme sollten nun auch sämtlich gefixt sein:

![Bildschirmfoto 2020-05-14 um 14 35 32](https://user-images.githubusercontent.com/612862/81935767-73c26c80-95f1-11ea-90e0-4f6231aad9e5.png)

**Comment by jcowey** [comment]
Fantastic and many thanks for making the Greek texts (in as much as they are present in github/master) of O.Krok. II appear.

**Comment by jcowey** [comment]
This now all works
