### ISSUE TITLE
Add P.Petra V metadata

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#102]
Add P.Petra V (p.petra;5;) metadata to
http://aquila.zaw.uni-heidelberg.de/
and
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc

**Comment by jcowey** [comment]
https://docs.google.com/spreadsheets/d/1BsCwRLttXG8N4hqyT7q1dpIFCxn9KQ5_AXcrz7kbVCA/edit#gid=0

**Comment by jcowey** [comment]
Hello, Carmen, you will find the FM file on .252 at
Admin/hgv/pPetra5
transfer_pPetra5.fmp12

All files are new.

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/98e39d4855119b63e99769f389c4f299a893a8c9

**Comment by Edelweiss** [comment]
[Aquila](https://aquila.zaw.uni-heidelberg.de/?search%5Boperator%5D=and&search%5Bcriteria%5D%5Bpublikation%5D%5Boperator%5D=cn&search%5Bcriteria%5D%5Bpublikation%5D%5Bvalue%5D=P.Oxyrhyncha&search%5BmentionedDates%5D=without&search%5Bmax%5D=100&search%5Bskip%5D=0&sort%5B1%5D%5Bkey%5D=publikationLang&sort%5B1%5D%5Bdirection%5D=ascend)

ok

[hgv.texte](https://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html)

[hgv.texte (github)](https://github.com/Edelweiss/hgv.texte/commit/66343f5dfcba1bbf997760b853d593cea96e246d)

**Comment by jcowey** [comment]
Super. Thank you.
