### ISSUE TITLE
Add P.Oxy. LXXXI metadata to aquilaHGV

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#106]
This is a case of adding a small Filemaker file to aquila FIlemaker master and then pushing that to aquila symphony.
All the hgv.texte files are present.

Four records were added to papyri.info:
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.oxy/p.oxy.81

These were not included in aquilaHGV!!!!

Create small file for these records in FM. Make relevant changes to hgv.texte 
https://github.com/Edelweiss/hgv.texte

(Liste, file for P.Oxy. 81)

**Comment by jcowey** [comment]
OK. Changes have now been made to 
https://github.com/Edelweiss/hgv.texte

All that needs to be done now is to create the actual records themselves.

**Comment by Edelweiss** [comment]
ok
[Aquila](https://aquila.zaw.uni-heidelberg.de/?search%5Boperator%5D=and&search%5Bcriteria%5D%5Bpublikation%5D%5Boperator%5D=cn&search%5Bcriteria%5D%5Bpublikation%5D%5Bvalue%5D=P.Oxy&search%5Bcriteria%5D%5Bband%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5Bband%5D%5Bvalue%5D=81&search%5Bcriteria%5D%5Bnummer%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5Bnummer%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BanderePublikation%5D%5Boperator%5D=sp&search%5Bcriteria%5D%5BanderePublikation%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Bort%5D%5Boperator%5D=sp&search%5Bcriteria%5D%5Bort%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Boriginaltitel%5D%5Boperator%5D=sp&search%5Bcriteria%5D%5Boriginaltitel%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Bmaterial%5D%5Boperator%5D=cn&search%5Bcriteria%5D%5Bmaterial%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Binhalt%5D%5Boperator%5D=sp&search%5Bcriteria%5D%5Binhalt%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Bbemerkungen%5D%5Boperator%5D=sp&search%5Bcriteria%5D%5Bbemerkungen%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Buebersetzungen%5D%5Boperator%5D=cn&search%5Bcriteria%5D%5Buebersetzungen%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Babbildung%5D%5Boperator%5D=sp&search%5Bcriteria%5D%5Babbildung%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Burl%5D%5Boperator%5D=cn&search%5Bcriteria%5D%5Burl%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BtmNr%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5BtmNr%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Bjahr%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5Bjahr%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Bmonat%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5Bmonat%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Btag%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5Btag%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BjahrIi%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5BjahrIi%5D%5Bvalue%5D=&search%5Bcriteria%5D%5Bjh%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5Bjh%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BjhIi%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5BjhIi%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BchronMinimum%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5BchronMinimum%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BchronMaximum%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5BchronMaximum%5D%5Bvalue%5D=&search%5Bcriteria%5D%5BchronGlobal%5D%5Boperator%5D=eq&search%5Bcriteria%5D%5BchronGlobal%5D%5Bvalue%5D=&search%5BmentionedDates%5D=without&sort%5B1%5D%5Bkey%5D=&sort%5B1%5D%5Bdirection%5D=ascend&sort%5B2%5D%5Bkey%5D=&sort%5B2%5D%5Bdirection%5D=ascend&sort%5B3%5D%5Bkey%5D=&sort%5B3%5D%5Bdirection%5D=ascend&sort%5B4%5D%5Bkey%5D=&sort%5B4%5D%5Bdirection%5D=ascend&sort%5B5%5D%5Bkey%5D=&sort%5B5%5D%5Bdirection%5D=ascend&search%5Bmax%5D=100&search%5Bskip%5D=0)

**Comment by jcowey** [comment]
Can you please have a look at this again. I think I made a mistake. Everything is OK apart from the title of the piece.

https://aquila.zaw.uni-heidelberg.de/hgv/704648

![Bildschirmfoto 2020-06-26 um 11 47 29](https://user-images.githubusercontent.com/612992/85844339-da1add00-b7a2-11ea-9dbf-f91f6c1f89a9.png)

P.Oxy. LXXX should be P.Oxy. LXXXI 

Would you please fix that.

**Comment by Edelweiss** [comment]
Ich verstehe nicht ganz die Tragweite dieses Phänomens?! Kurz telefonieren?

**Comment by Edelweiss** [comment]
Verstehe!

![Bildschirmfoto 2020-06-26 um 11 59 41](https://user-images.githubusercontent.com/612862/85845525-accf2e80-b7a4-11ea-89d9-76db6ea1f650.png)

**Comment by Edelweiss** [comment]
PublikationL(ang) muss überall geändert werden, also vermutlich auch in idp.data?! Muss mal schauen…

**Comment by jcowey** [comment]
Should be OK in idp.data, because these four texts were entered via the editor and not through a xwalk.

**Comment by jcowey** [comment]
Looking good in Aquila now. Thank you.

**Comment by Edelweiss** [comment]
Ah, okay… Dann sollte jetzt alles soweit gefixt sein.

**Comment by Edelweiss** [comment]
In FileMaker auch

**Comment by jcowey** [comment]
Splendid. Thanks.

**Comment by jcowey** [comment]
Everything now OK
