### ISSUE TITLE
Add P.Oxyrhyncha metadata

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#107]
Add P.Oxyrhyncha (p.oxyrhyncha) metadata to
http://aquila.zaw.uni-heidelberg.de/
and
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc

**Comment by jcowey** [comment]
https://docs.google.com/spreadsheets/d/1N0SKCFWjOlMCYAHyJrpaBEFQibUAZwErxQcmpRAohYg/edit#gid=0

**Comment by jcowey** [comment]
Hello, Carmen, you will find the FM file on .252 at
Admin/hgv/pOxyrhyncha
transfer_pOxyrhyncha.fmp12

**Comment by Edelweiss** [comment]
Probleme beim xWalk…

**Comment by Edelweiss** [comment]
(1) Textstring im Jahresfeld (muss eigentlich in Erg-Feld geschrieben werden)

![Bildschirmfoto 2020-06-25 um 10 53 04](https://user-images.githubusercontent.com/612862/85691500-d882e380-b6d4-11ea-96f3-cff89cefaf5f.png)

**Comment by Edelweiss** [comment]
(2) Veränderte Formel für TexIDLang (fehlendes Leerzeichen)

![Bildschirmfoto 2020-06-25 um 11 09 07](https://user-images.githubusercontent.com/612862/85691784-18e26180-b6d5-11ea-8be4-0e3e8453f5fc.png)

**Zum Vergleich vom letzten xWalk**
![Bildschirmfoto 2020-06-25 um 11 09 29](https://user-images.githubusercontent.com/612862/85691795-1b44bb80-b6d5-11ea-85f5-fb503971ef30.png)

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/91bfe2b264d070bf6d12881600827c7fce64f47c

**Comment by Edelweiss** [comment]
ok

[Aquila](https://aquila.zaw.uni-heidelberg.de/?search%5Boperator%5D=and&search%5Bcriteria%5D%5Bpublikation%5D%5Boperator%5D=cn&search%5Bcriteria%5D%5Bpublikation%5D%5Bvalue%5D=P.Oxyrhyncha&search%5BmentionedDates%5D=without&search%5Bmax%5D=100&search%5Bskip%5D=0&sort%5B1%5D%5Bkey%5D=publikationLang&sort%5B1%5D%5Bdirection%5D=ascend)

[hgv.texte](https://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html)

[hgv.texte (github)](https://github.com/Edelweiss/hgv.texte/commit/66343f5dfcba1bbf997760b853d593cea96e246d)

**Comment by jcowey** [comment]
Super. Thank you.
