### ISSUE TITLE
DDB split (rom.mil.rec;1;78)

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/hgv#114]
https://docs.google.com/spreadsheets/d/14_pLbcUvF8qPnVkCnLNIifK5882ERwWapPyDSEmZsV4/edit#gid=0

Beispiel

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/rom.mil.rec/rom.mil.rec.1/rom.mil.rec.1.78.xml

http://papyri.info/hgv/45124
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.wilck/o.wilck.1134.xml
76 further divs

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/64c05e2f9c701b9ec47b518fd102c79546b1ff04

**Comment by Edelweiss** [comment]
next steps

- change ddb-hybrid and ddb-filename in HGV
- change reprint-in in DDB
- delete original file

**Comment by jcowey** [comment]
The commit papyri/idp.data@64c05e2 certainly now looks good to me.

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/42dd1ccac033f1f509d1f9ab853226576b89a441

**Comment by Edelweiss** [comment]
O.Bodl 12.2031 and O.Bodl 12.2006 don’t exist

(TM 72704 & 72682)

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/rom.mil.rec/rom.mil.rec.1/rom.mil.rec.1.78.xml#L309

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/rom.mil.rec/rom.mil.rec.1/rom.mil.rec.1.78.xml#L336

**Comment by Edelweiss** [comment]
correct O.Bodl 12.2031 and O.Bodl 12.2006

https://github.com/papyri/idp.data/commit/d6dcd452e6423668687dd965cd8269a463f24f47
https://github.com/papyri/idp.data/commit/ad282d0975e8b0fa2d5c719b932f8937e686fbf3
https://github.com/papyri/idp.data/commit/fbfb7b63ad559e8af2ebe6f6918a34bb3b6212ce

**Comment by Edelweiss** [comment]
next steps

- change ddb-hybrid and ddb-filename in HGV
- double reprints
- delete original file

**Comment by Edelweiss** [comment]
double references

https://github.com/papyri/idp.data/commit/1bd04c1647956f7bc25a5b3d0095e615ca7938b2

**Comment by Edelweiss** [comment]
update HGV idnos

https://github.com/papyri/idp.data/commit/f2400453c6e06af78e20b46703d49584099a7abf

**Comment by jcowey** [comment]
All looking good to me. I have checked the commits

**Comment by Edelweiss** [comment]
final step

- delete original file

**Comment by Edelweiss** [comment]
file deleted

https://github.com/papyri/idp.data/commit/33720a087619f82d35cea17879bd0352f036fb4c
