### ISSUE TITLE
Images for Digital Bodleian

### ISSUE THREAD

**Issue by samosafuz** [Edelweiss/hgv#154]
The Bodleian Library in Oxford has encoded its catalogue of Western Manuscripts in TEI xml, and has published the repo in [GitHub](https://github.com/bodleian/medieval-mss). This xml is sufficiently well structured, such that it includes TM numbers for ancient texts as well as links to its [Digital Bodleian](https://digital.bodleian.ox.ac.uk) portal where these links are available. It is therefore now possible (and desirable) to automate the updating of image links in HGV and DCLP. 

Could you work up a script for doing so? The pertinent folders in the repo will be those with the prefixes `Gr_` (for Greek, e.g., `/collections/Gr_bib`) or `Lat_` (for Latin, e.g., `/collections/Lat_bib`).

It shouldn't have much trouble to compile the pertinent data: so, for example, in the file for [MS. Gr. class. d 100 (p)](https://github.com/bodleian/medieval-mss/blob/1d248c6cebcd2bf3c0c13bfdba51ba0651f85360/collections/Gr_class/MS_Gr_class_d_100_P.xml#L62-L65) one finds
```
                     <bibl subtype="full" type="digital-facsimile">
                        <ref target="https://digital.bodleian.ox.ac.uk/objects/3f5a2ed9-9d4d-4032-94c8-7d6c0fa259b3/">
                        <title>Digital Bodleian</title></ref> <note>(full digital facsimile)</note>
                     </bibl>
```
as well as a pair of TM numbers: 
```
                  <altIdentifier type="external">
                     <idno type="TM">20349</idno>
                  </altIdentifier>
                  <altIdentifier type="external">
                     <idno type="TM">20343</idno>
                  </altIdentifier>
```
It's a shame these links don't take the form of DOIs or other stable identifiers, but we can hope that they're going to be around for a while.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/pull/333

Now merged.
