### ISSUE TITLE
Import P.Flor. and PUG Image Links

### ISSUE THREAD

**Issue by samosafuz** [Edelweiss/hgv#158]
I've worked up [a spreadsheet](https://docs.google.com/spreadsheets/d/1Pn0HH3MA9wnvXMaa0BOTHgb5SmiLbQT3k-6si4HSVa0/edit#gid=0) with ca. 550 image links for P.Flor. and PUG texts, and would ask that you undertake to import them into HGV and DCLP.

Two additional notes on this request:

1. Some of the files (in HGV, especially) will already have had the link added manually. Avoiding duplication is important.
2. Several TM numbers appear twice in column A (I have highlighted them with conditional formatting) because there are multiple entries in the PSI online database for them. A good example is TM 14242, which points both to [P.Flor. 2.165](http://www.psi-online.it/documents/pflor;2;165) and [P.Flor. 2.264](http://www.psi-online.it/documents/pflor;2;264). Although it looks as though the image and metadata in both instances is the same, I nonetheless recommend that we add both hyperlinks.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/pull/353

Should have fixed this. Waiting to close once sync has chewed through the files.

**Comment by jcowey** [comment]
This now looks good.
