### ISSUE TITLE
"Texte" problem

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#16]
I've noted one problem using the 'Texte' search route which affects P.Flor. II and maybe other volumes (I haven't checked systematically): when I select a text by volume and number it comes up fleetingly in the normal frame to the right, then as a full-page display; from the full page display I can't return to the page with volumes and numbers to the left - if I use the return arrow the previous page appears fleetingly with the (previously) selected text in the frame to the right, then reverts to the full-page display of that text. Hope that's clear.
noted by Dominic Rathbone 24.03.2014

**Comment by Edelweiss** [comment]
Wrong HGV hooks (is http://aquila/.../tm, should be http://aquila/.../ddb)

Affects

P.Bingen (1x)
P.Flor. II (197x)
P.Thomas (3x)

**Comment by Edelweiss** [comment]
https://github.com/Edelweiss/hgv.texte/commit/46f49b4777950f1cc7e49c47adaf0584e502072d
https://github.com/Edelweiss/hgv.texte/commit/d2e468b8a08606f1ab054fbef87e647654cd27b3
https://github.com/Edelweiss/hgv.texte/commit/3db5dd0c2277d710734e18cd50a2c127c0a56af9
https://github.com/Edelweiss/hgv.texte/commit/d7f97949ec576cccdecc045e26ea247dcc4a9927
