### ISSUE TITLE
P.KölnSarapion in Aquila HGV bug

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#163]
If one uses http://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html to navigate to P.KölnSarpion and then clicks on it, "Oops! An Error Occurred" is the message one gets. 

Can you please sort this out so that it works properly. 

The records for P.KölnSarapion are visible in the following way:

https://aquila.zaw.uni-heidelberg.de/hgv/977101

**Comment by Edelweiss** [comment]
https://github.com/Edelweiss/hgv/commit/cb7b060abc94aadefb2de06250932f7beba0eefa
