### ISSUE TITLE
Deploy commit to aquila HGV

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#166]
I corrected a minor inaccuracy with the following commit at https://github.com/Edelweiss/hgv.texte/tree/master/Ostraka:

https://github.com/Edelweiss/hgv.texte/commit/70f190cd7c01d09d0aed9a13158430232ff70ea1

Would you please deploy it so that it shows up in the Aquila HGV in HGV-Texte at the relevant place

**Comment by Edelweiss** [comment]
https://github.com/Edelweiss/hgv/commit/75e917e11c133b056221159e4a6c4a848c41e038

**Comment by jcowey** [comment]
Thanks
