### ISSUE TITLE
Make 70109 show up

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#180]
Neither https://papyri.info/ddbdp/rom.mil.rec;1;11

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/rom.mil.rec/rom.mil.rec.1/rom.mil.rec.1.11.xml

nor https://papyri.info/hgv/70109 

https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV71/70109.xml

displays

**Comment by samosafuz** [comment]
This is now fixed. 

https://papyri.info/ddbdp/rom.mil.rec;1;11 had `reprint-in` where it should have had `reprint-from` (so both `rom.mil.rec;1;11` and `stud.pal;14;8C` had `reprint-in` dummy headers pointing to one another, in a recursive loop that no doubt confused the numbers server.)

I wonder whether Carmen can cook up something to check if such a recursive loop occurs elsewhere (gasp!).

In any event, this ticket can now be closed.

**Comment by samosafuz** [comment]
Follow-up is now a standalone ticket: #190.
