### ISSUE TITLE
Add new image links to P.Merton files

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#193]
WIth the help of this spreadsheet:

https://docs.google.com/spreadsheets/d/1wqsVOs8lAwpDulwLLkZQ4LD0F-G_rbVzo8uLB9hB_Jo/edit#gid=0

please add image links to the relevant DCLP / HGV files.

Links to DCLP / HGV files in the github repo.

Links to HGV files in aquila, as well, please.

**Comment by Edelweiss** [comment]
auch in Aquila HGV

**Comment by jcowey** [comment]
Now done.
