### ISSUE TITLE
Receuil I+II 14 not functioning in Texte im HGV 

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#26]
In:
http://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html
Recueil I+II 14 does not work. Not sure what causes the problem in:
```<P><A HREF="http://aquila.zaw.uni-heidelberg.de/ddb/Recueil;;;14;;" TARGET="HGV">Recueil I+II 14</A></P>```
Presumably ```Recueil;;;14;;``` is inaccurate
The value in zusBand is "I+II". Do I have to give "+" special treatment in the HTML file?
TM_Nr. = 13879

**Comment by Edelweiss** [comment]
Wenn man `%25252B` statt `+` oder `%2B` nimmt geht’s es. Es ist wohl eine php-Eigenart:

Beispiel:

http://147.142.225.252/hgv.dev/app_dev.php/ddb/Recueil;;I%25252BII;14;;

**Comment by jcowey** [comment]
Super thanks. It now works live!
