### ISSUE TITLE
P.Gen. I (2e éd.) also not functioning in Texte im HGV

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#27]
http://www.rzuser.uni-heidelberg.de/~gv0/Texte/HGV-Texte.html
shows
 P.Gen. I (2e éd.)
P.Gen. II
P.Gen. III
P.Gen. IV
which is what we have in 
http://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html
so that step is presumably OK.
None of the links work, however.
http://papyri.info/ddbdp/p.gen.2;1;1
gives the TM_Nr. 11211
as the number for  P.Gen. 1 (2e éd.) 1

"(2e éd.)" is the value in zusBand

**Comment by Edelweiss** [comment]
[P.Gen. I (2e éd.)](https://github.com/Edelweiss/hgv.texte/commit/d4767e40e370f3f9683dbe310c5be189a928644d) fixed

**Comment by Edelweiss** [comment]
Broken links in P.Gen. II

- P.Gen. II 103 Kol. I - Kol. II 9

**Comment by jcowey** [comment]
Just checked a number of them. The fix is great!

**Comment by Edelweiss** [comment]
[P.Gen. II](https://github.com/Edelweiss/hgv.texte/commit/fe5878d16b7faeb59ba25d28ef8c6e8e3f16fde5) fixed

**Comment by jcowey** [comment]
Indeed. Brilliant. Closing this now.
