### ISSUE TITLE
Non functional links Washington (omeka.wustl.edu)

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#33]
washington images:
http://library.wustl.edu/units/spec/manuscripts/papyri/wtu.inventory.161.html
in
http://papyri.info/ddbdp/p.wash.univ;1;2

**Comment by jcowey** [comment]
http://omeka.wustl.edu/omeka/exhibits/show/papyri-collection/item/8060

**Comment by jcowey** [comment]
palau.rib
oslo
monts.roca
matr
leipz
columbia
gron

**Comment by jcowey** [comment]
See the following spreadsheet:

https://docs.google.com/spreadsheets/d/1UaHgLhVWrSEJVRHS8SPLh9CEuKfukuWL7BVcDgJwi0k/edit#gid=0

**Comment by jcowey** [comment]
Would you please use the above mentioned googlespreadsheet (https://docs.google.com/spreadsheets/d/1UaHgLhVWrSEJVRHS8SPLh9CEuKfukuWL7BVcDgJwi0k/edit#gid=0) to make the relevant changes in the master github repository. 

Then also make the changes in HGV Filemaker and import to MySQL database.

**Comment by Edelweiss** [comment]
Doppelte TM-Nummern:

TM 30767
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV31/30767.xml,http://omeka.wustl.edu/omeka/items/show/7836
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV31/30767.xml,http://omeka.wustl.edu/omeka/items/show/7847

**Comment by Edelweiss** [comment]
Column I

- TM 30255
- TM 35971
- TM 25299

**Comment by Edelweiss** [comment]
Ohne bestehende tei:graphic/@url:

TM 32900

**Comment by Edelweiss** [comment]
```
git checkout HGV_meta_EpiDoc/HGV31/30767.xml HGV_meta_EpiDoc/HGV36/35760.xml HGV_meta_EpiDoc/HGV31/30255.xml HGV_meta_EpiDoc/HGV36/35971.xml HGV_meta_EpiDoc/HGV26/25299.xml
```

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/5b3078a34a53653833779bec75745f51c64ec7e2
https://github.com/papyri/idp.data/commit/770077ac934c3559e98c89d01cffb0f7f5bfedf2
https://github.com/papyri/idp.data/commit/c1a092d1a87e3012cf2aa3226fcdce0ba1524f44

**Comment by Edelweiss** [comment]
Zum Beispiel:
http://aquila.zaw.uni-heidelberg.de/hgv/25299

**Comment by Edelweiss** [comment]
siehe auch #46

**Comment by jcowey** [comment]
Now in both papyri.info and aquila
