### ISSUE TITLE
Reload O.Ber. III and update Texte_im_HGV

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#40]
I went through the TM_Nr. field in master HGV on 147.142.225.252 for all records entered on 30.03.2017 (in field last modified). There should now be NO trailing white space. Would you please:

- upload all those records to the MySQL database so that they are all visible and clickable in 
http://aquila.zaw.uni-heidelberg.de/
- update hgv.texte to include and make available all the changes I committed to it:
- redo a xwalk for papyri.info (remembering that it is important to catch the content of the field ddbSerIDP - "o.berenike" for the idnos)

**Comment by Edelweiss** [comment]
Fix for mysql database:

UPDATE hgv SET hgvId = TRIM(hgvId) WHERE modifiedAt LIKE '2017-03-30%'

**Comment by Edelweiss** [comment]
Fix for FileMaker database:

- Datensätze heraussuchen (z.B. über modifiedAt)
- Feldinhalt ersetzen (über Menü)
- Durch berechneten Wert ersetzen
- Trim-Funktion auswählen

**Comment by Edelweiss** [comment]
Update hgv.texte

```
 Liste.html              |    1 +
 Ostraka/O.Ber._I.html   |    2 +-
 Ostraka/O.Ber._II.html  |    2 +-
 Ostraka/O.Ber._III.html |  263 +++++++++++++++++++++++++++++++++++++++++++++++
 P.Pintaudi.html         |    2 +-
 P.Poethke.html          |    6 +-
 SB/SB_XXVIII.html       |    2 +-
 7 files changed, 271 insertions(+), 7 deletions(-)
 create mode 100644 Ostraka/O.Ber._III.html
```

**Comment by jcowey** [comment]
Excellent. Preserving the update info on hgv.texte is good and something we should remember to continue in the future.
Everything seems now to work fine.
