### ISSUE TITLE
Fix P.Berl. Bork in Texte

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#41]
Clicking on P.Berl. Bork in Texte
lands on at

Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please e-mail us at [email] and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by Edelweiss** [comment]
Gültige Links derzeit:

Publikation, Band*, ZusBand*, Nummer, Seite*, zusaetzlich*

ODER

Publikation, Band*, ZusBand*, Nummer*, Seite*, zusaetzlich

ODER

Publikation Band* Nummer

**Comment by Edelweiss** [comment]
`/ddb/P.Berl. Bork.;;;;;` muss ebenfalls zugelassen werden.

**Comment by Edelweiss** [comment]
Neue Regel:

**Publikation;;;;;**

**Comment by Edelweiss** [comment]
ok, [test](http://aquila.zaw.uni-heidelberg.de/ddb/P.Berl.%20Bork.;;;;;)

**Comment by jcowey** [comment]
Looks good thank you. And yes I am afraid we have to make allowance for such cases.
