### ISSUE TITLE
Correct ONB links

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#43]
Using the following change and replace 

`<graphic url="http:\/\/aleph\.onb\.ac\.at/F/\?func=find-c&amp;ccl_term=WID%3D(RZ\d+)&amp;local_base=ONB08"/>`

with 

`<graphic url="http://data.onb.ac.at/rec/\1"/>`

Make the links to the ONB work again

**Comment by jcowey** [comment]
This commit:

https://github.com/papyri/idp.data/commit/6c9ad1abdd6304db75bc953e68ff48e5de316390

and this one:

https://github.com/papyri/idp.data/commit/eafdb3d435e1c1973e7bf7558d891fa3142feda2

solved this for papyri.info.

Still has to be done for aquila

**Comment by Edelweiss** [comment]
siehe #46
