### ISSUE TITLE
Correct Oslo links (ub-fmserver.uio.no)

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#45]
Replace 

`<graphic url="http://wwwapp\.cc\.columbia\.edu/ldpd/app/apis/item\?mode=item&amp;key=oslo\.apis\.(\d+)"/>`

with 

`<graphic url="http://ub-fmserver.uio.no/viewRecord.php?recid=\1"/>`

**Comment by jcowey** [comment]
Also has to be imported into / changed in FileMaker and then MySQL

**Comment by Edelweiss** [comment]
siehe #46

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/0c4769d87cce39cfe2155af52345cb4abbfa4d42

**Comment by Edelweiss** [comment]
Zum Beispiel:
http://aquila.zaw.uni-heidelberg.de/hgv/14273

**Comment by jcowey** [comment]
These are now in both papyri.info and aquila
