### ISSUE TITLE
Alter image links to manchester collection

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#53]
Example
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV13/12900.xml#L115
had
```<graphic url="http://enriqueta.man.ac.uk/luna/servlet/view/search?q==%22Greek%20Papyrus%20104%22"/>```

now has (I added it to test it out)

```<graphic url="https://luna.manchester.ac.uk/luna/servlet/view/search?q=metadata_schema=12900"/>```

As you can see the new link is built from 
https://luna.manchester.ac.uk/luna/servlet/view/search?q=metadata_schema=
plus
relevant TM number

In the spreadsheet I have prepared it all
https://docs.google.com/spreadsheets/d/1A7-PYgkKJx4fDtNut7-Q2qrKcjElwVKJvgI_tEHrfdc/edit#gid=0

Tested a few of the links.

In rows 130 and 131 (in yellow there are texLetts)
It seems that by just taking the TM number we get workable links.

Would you please make the relevant changes in papyri.info and simply commit straight to master.

Then the same in Filemaker (possibly the Filemaker scripting may be the most efficient way) and push to aquila

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/82d07bfe3d7345dfd1a025ab3d59d53bebbaa49b

**Comment by jcowey** [comment]
Magic thanks!

**Comment by jcowey** [comment]
https://luna.manchester.ac.uk/luna/servlet/view/search?q=metadata_schema=17314

leads to nothing

**Comment by Edelweiss** [comment]
Bei mir kommt bei beiden Links der gleiche Papyrus, nur einmal kommt er als Suchergebnis wie bei allen anderen Links, die ich heute bearbeitet habe, und einmal kommt er als Übersichtsseite mit großformatigem Bild und Medieninformationen.

**Comment by Edelweiss** [comment]
Nun auch in FileMaker

**Comment by Edelweiss** [comment]
Nun auch auf Aquila, z.B.

https://aquila.zaw.uni-heidelberg.de/hgv/12900

**Comment by jcowey** [comment]
Does the link work for you? My firefox is not showing it

**Comment by Edelweiss** [comment]
Nein, der https-Inline-Frame funktioniert auch bei mir nicht

**Comment by jcowey** [comment]
https://luna.manchester.ac.uk/luna/servlet/view/search?q=metadata_schema=12980

is not working for me any longer

I took it from the googlespreadsheet

which worked earlier this morning. Very strange!

**Comment by Edelweiss** [comment]
Doch der Link funktioniert!

**Comment by Edelweiss** [comment]
Nur der Inline-Frame ist leer.

**Comment by jcowey** [comment]
Must be my browser
