### ISSUE TITLE
Add PUG IV metadata

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#56]
Add PUG (p.genova;4;) metadata to 
http://aquila.zaw.uni-heidelberg.de/
and
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc

FM file nearly ready

**Comment by jcowey** [comment]
FM file: pGenova4trans.fmp12 now ready.

**Comment by jcowey** [comment]
Carmen you will find the file `pGenova4trans.fmp12` at ../Admin/hgv/ on the 252 server. Would you please also make and install the files for `Texte im HGV` as described in the comment above.

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/34849ee32b3ef173c851e55c9314519677346143
https://github.com/papyri/idp.data/commit/1d8c0fdf1b1bf4c5b73cac33d02cf72c1f4d558b

**Comment by jcowey** [comment]
Being processed for 
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc
by
https://github.com/papyri/idp.data/issues/84
