### ISSUE TITLE
Add P.Bastianini metadata

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#64]
Add P.Bastianini (p.bastianini;;) metadata to
http://aquila.zaw.uni-heidelberg.de/
and
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc

**Comment by jcowey** [comment]
https://docs.google.com/spreadsheets/d/1ygdo1hbebw8obLbQxORALrVh9q2YyCk25mZQ6Sij1fU/edit#gid=0

**Comment by jcowey** [comment]
All 16 records are NEW.

**Comment by jcowey** [comment]
Do the remainder of the work in FileMaker. There is already a file with many of the details.

**Comment by jcowey** [comment]
You will find the FM file on .252 at
Admin/hgv/pBastianini
transfer_pBastianini_Carmen.fmp12

**Comment by Edelweiss** [comment]
zu HGV.Texte

wo soll P.Bastianini dort untergebracht werden. Es gibt noch nichts dieses Namens. Auf papyri.info auch nicht, obwohl die Zählung bei 11 beginnt und von daher zu erwarten wäre, dass 1-10 schon existieren.

**Comment by Edelweiss** [comment]
```HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional>
<HTML>
<HEAD>
  <TITLE>P.Bas.</TITLE>
<link rel="stylesheet" type="text/css" href="HGV-Paragr.css">
</HEAD>
<BODY bgcolor="white">
<H2 ALIGN=CENTER>P.Bas.</H2>

<P></P>

<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;11;;" TARGET="HGV">P.Bastianini 11</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;12;;" TARGET="HGV">P.Bastianini 12</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;13;;" TARGET="HGV">P.Bastianini 13</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;14;;" TARGET="HGV">P.Bastianini 14</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;15;;" TARGET="HGV">P.Bastianini 15</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;16;;" TARGET="HGV">P.Bastianini 16</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;17;;" TARGET="HGV">P.Bastianini 17</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;18;;" TARGET="HGV">P.Bastianini 18</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;19;;" TARGET="HGV">P.Bastianini 19</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;20;;" TARGET="HGV">P.Bastianini 20</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;21;;" TARGET="HGV">P.Bastianini 21</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;22;;" TARGET="HGV">P.Bastianini 22</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;23;;" TARGET="HGV">P.Bastianini 23</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;24;;" TARGET="HGV">P.Bastianini 24</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;25;;" TARGET="HGV">P.Bastianini 25</A></P>
<P><A HREF="https://aquila.zaw.uni-heidelberg.de/ddb/P.Bastianini;;;26;;" TARGET="HGV">P.Bastianini 26</A></P>

</BODY>
</HTML>

```

**Comment by Edelweiss** [comment]
Ich gehe mal davon aus, dass das HTML dazu so aussehen müsste.

**Comment by jcowey** [comment]
P.Bastianini 1-10 are literary pieces and do not interest us in terms of HGV.

**Comment by Edelweiss** [comment]
Ah, ok, also eine neue Datei anlegen.

**Comment by jcowey** [comment]
Between these two

  
![Bildschirmfoto 2020-05-28 um 14 55 37](https://user-images.githubusercontent.com/612992/83144217-5b734700-a0f3-11ea-9a04-41138f03837a.png)

**Comment by jcowey** [comment]
Yes the new file P.Bastianini.html should be placed between 
P.Bas.html
and
P.Bawit_Clackson.html

**Comment by Edelweiss** [comment]
Okay, dann wäre ich soweit mit allem durch

**Comment by jcowey** [comment]
Looked through
http://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html

Checked P.Bastianini. Perfect.
Merged the pull request. The files looked super clean. 
Many thanks, that is excellent

**Comment by jcowey** [comment]
Now is traceable in papyri.info
http://papyri.info/search?SERIES=P.Bastianini&VOLUME=
