### ISSUE TITLE
Add P.Trier I metadata

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#65]
Add P.Trier (p.trier;1;) metadata to
http://aquila.zaw.uni-heidelberg.de/
and
https://github.com/papyri/idp.data/tree/master/HGV_meta_EpiDoc

**Comment by jcowey** [comment]
See:
https://docs.google.com/spreadsheets/d/1ZBHuV2xBZmfmHsCJWWQuCnsXj-vie6YVjfVaDHcMHzA/edit#gid=0

**Comment by jcowey** [comment]
Hello, Carmen, you will find the FM file on .252 at
Admin/hgv/pTrier
transfer_pTrier_Carmen.fmp12

**Comment by jcowey** [comment]
For
https://github.com/Edelweiss/hgv.texte
please create a new folder and put it between

![Bildschirmfoto 2020-06-18 um 10 50 31](https://user-images.githubusercontent.com/612992/84999548-9b0cdc00-b151-11ea-99c0-62ff2163d604.png)

**Comment by Edelweiss** [comment]
Alles neu für…

Aquila FileMaker 
Aquila mySQL
Aquila HGV Texte
idp.data?

**Comment by jcowey** [comment]
Yes please!
For Aquila and for papyri.info.

**Comment by jcowey** [comment]
I also added a little further note above, which I will repeat here:

All files are new (there are only 14 files) [16 in Filemaker, because of the Alternativedatierungen for 703238X and 703238Y as well as 703239X and 703239Y]

**Comment by Edelweiss** [comment]
https://aquila.zaw.uni-heidelberg.de/texte/HGV-Texte.html

https://github.com/papyri/idp.data/commit/4bfded1c00d82595b92b90c671183632f13dc81f

**Comment by jcowey** [comment]
Files for idp.data look very good, thanks. Would you please make a pull request so that I can merge them.

HGV-Texte all works beautifully, thank you. Wow that was a quick turn around.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/pull/151/commits/4bfded1c00d82595b92b90c671183632f13dc81f

added to master by

https://github.com/papyri/idp.data/pull/151

**Comment by jcowey** [comment]
Τhe folder P.Trier is not appearing here:
https://github.com/Edelweiss/hgv.texte
I think you have to remember to make the commit, so that all the changes are reflected in
https://github.com/Edelweiss/hgv.texte

**Comment by jcowey** [comment]
Now all visible.
