### ISSUE TITLE
Missing Biblio files ??

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#68]
Please check that 

https://github.com/papyri/idp.data/tree/master/Biblio

really includes every file that was added to the DCLP branch of biblio. I would like to be sure that no file has "gone missing"

**Comment by Edelweiss** [comment]
**Letzter commit vor dem Merge**

commit **ab254073867f77ac1cb3633a1821340d659ee808**
Author: James Cowey <james.cowey@urz.uni-heidelberg.de>
Date:   **Tue Jan 8 05:16:20 2019** -0500

    Update revisionDesc
    
     - Submit - Added image link (James Cowey)
     - Vote - HGVAccept - Fine (James Cowey)
     - Finalized - Ready. (James Cowey)

**Probleme**

* 81955 deleted, but 82260 points to it

**Diff zwischen einem commit und heute**

```
git diff --diff-filter=DMR ab254073867f77ac1cb3633a1821340d659ee808 HEAD Biblio/
```

**Rollback zu einen bestimmten Zeitpunkt**

```
git checkout "`git rev-list master -n 1 --first-parent --before=2019-01-01`"
```
(20910db2c8f9967f42b474bd695ba18218de84ff)
