### ISSUE TITLE
BL 12 entry from Spreadsheet

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#71]
I have done as much as I can to get things in order.
https://docs.google.com/spreadsheets/d/1EWK_SVCEov1aCbt8EVpKlY8i0r17KAPLrlnGgYXVg2A/edit#gid=0

Marked in orange in the `edition sort` column are 3 or 4 volumes for which we do not have a relevant entry and number. Would you please create them as appropriate.

I also did not fill up all the blanks in `text` and `edition sort`

**Comment by jcowey** [comment]
Please go ahead and import all of the remaining sheets (marked with light purple colour)

**Comment by Edelweiss** [comment]
Wir brauchen neue Editonen für Chartae Latinae 41 und 45

Chartae Latinae|   |Sort |  
-- | -- | -- | --
**Chartae Latinae 30** |   | **234000** |  
Chartae Latinae 31 |   | 234077 | 77
Chartae Latinae 32 |   | 234154 | 77
Chartae Latinae 33 |   | 234231 | 77
Chartae Latinae 34 |   | 234308 | 77
Chartae Latinae 35 |   | 234385 | 77
Chartae Latinae 36 |   | 234462 | 77
Chartae Latinae 37 |   | 234539 | 77
Chartae Latinae 38 |   | 234616 | 77
Chartae Latinae 39 |   | 234693 | 77
Chartae Latinae 40 |   | 234770 | 77
Chartae Latinae 41 |   | 234847 | 77
Chartae Latinae 42 |   | 234924 | 77
**Chartae Latinae 43** |   | **235000** | 76
Chartae Latinae 44 |   | 235250 | 250
Chartae Latinae 45 |   | 235500 | 250
Chartae Latinae 46 |   | 235750 | 250
**Chartae Latinae 47** |   | **236000** | 250

**Comment by Edelweiss** [comment]
Wäre es hilfreich gleich alle anzulegen, oder lieber nur die aktuell benötigten?

**Comment by Edelweiss** [comment]
passim

![Bildschirmfoto 2019-03-13 um 13 30 01](https://user-images.githubusercontent.com/612862/54278979-2fbe7c80-4594-11e9-813a-848d65069803.png)

In diesem Fall keine
* DDB-Angaben
  * ddb
  * collection
  * volume
  * document
* HGV-Angaben
  * HGV
  * TM
  * Folder
* Positionsangaben
  * position

**Comment by Edelweiss** [comment]
Ist es okay, wenn Text leer ist?

![Bildschirmfoto 2019-03-13 um 15 59 34](https://user-images.githubusercontent.com/612862/54289237-15db6480-45a9-11e9-9283-378ac95c2910.png)

Es gibt unter 6658 Datensätzen nur vier dieser Art.

**Comment by jcowey** [comment]
These four look somewhat odd, but because they are marked as finalised they are maybe not imports.

**Comment by jcowey** [comment]
It would be worth "gleich alle anzulegen".

**Comment by jcowey** [comment]
Only just arrived in Lund now!

**Comment by Edelweiss** [comment]
Sorry, ich erwarte keine Antworten. Ich nutze das Ticket nur als Gedächtnisprotokoll! Viel Spaß in Lund.

**Comment by Edelweiss** [comment]
Und gleich nochmals sorry, ich bezweifle inzwischen, dass ich in dieser Wochen mit den zu importierenden Daten fertig werden kann, geschweige denn ein weiteres Ticket anfangen kann.

**Comment by jcowey** [comment]
Kein Problem! If there are big difficulties then let us wait until next week. If you can point me to the difficulties that would be helpful. If not then we can deal with it next week.

**Comment by jcowey** [comment]
There are still improvements and completion of data that I could add to the googlespreadsheet, if you have not already imported data.

**Comment by jcowey** [comment]
By looking at production it seems that you have not done any lasting import. Perhaps if you could let me know where you stand tomorrow morning I can have a look. 
A morning of work is sort of planned

**Comment by jcowey** [comment]
By the way the first sheet 46to56 was complete as far as I was concerned. I had not filled out filled out columns C and H. I see that you HAVE filled these out. A possibility might be to try to focus on importing that specific sheet. Let me know what you think

**Comment by jcowey** [comment]
All done now.
