### ISSUE TITLE
TM-Nummer deprecated

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/hgv#74]
Diese beiden Dateien haben lediglich deprecated idnos für TM

Außerdem trailing Leerzeichen in TEI::idno tag.

https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV31/30425.xml

https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV9/8692.xml

Deswegen wurde diese nicht importiert in BL:register.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV31/30425.xml
should now be correct as a result of
https://github.com/papyri/idp.data/commit/e337b6c3cf75c5de728601a039ac52e8edd4cf7a

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV9/8692.xmlshould now be correct as a result of
https://github.com/papyri/idp.data/commit/072fb5d50c2949e651d03ff75f53835cc8045540

**Comment by jcowey** [comment]
Both should now be fixed
