### ISSUE TITLE
Add biblio reference for West Homer into DCLP files

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/hgv#94]
Please add the following code to DCLP files in master.

Using the spreadsheet
https://docs.google.com/spreadsheets/d/1MvSKzKpHQeZuk2aUHTRGf50fzfnIqFt5BXTe-cuf9RU/edit#gid=0

Add the relevant information at the corresponding place in each file. This is a model of how it should be done.

https://github.com/papyri/idp.data/blob/master/DCLP/61/60861.xml#L182-L187

```
               <bibl n="2" type="reference" subtype="catalogue">
            <!-- ignore - start, i.e. SoSOL users may not edit this -->
            <!-- ignore - stop -->
                  <ptr target="http://papyri.info/biblio/16711"/>
                  <biblScope unit="number">109</biblScope>
               </bibl>
```

The value / content of the `<biblScope unit="number">` is the value / content found in column `c` of the spreadsheet.

Some of these numbers have already been entered using the editor for DCLP entry. For this reason it would probably be wise to check in advance and exclude those TM numbers from the list. Or perhaps match and overwrite.

**Comment by Edelweiss** [comment]
Hier fehlt die TM-Nummer

https://docs.google.com/spreadsheets/d/1MvSKzKpHQeZuk2aUHTRGf50fzfnIqFt5BXTe-cuf9RU/edit#gid=0&range=1452:1452

Vermutlich **68496**

**Comment by jcowey** [comment]
Your assumption was correct. I have added **68496**. I checked it.
https://www.trismegistos.org/text/68496

**Comment by Edelweiss** [comment]
Testbeispiele:

**schon drin (siehe oben)**
git diff DCLP/61/60861.xml

**neue principal edition (siehe oben)**
git diff DCLP/62/61258.xml

**mehrfache vorkommende TM**
git diff DCLP/61/60260.xml

**Hinzufügen zu bestehender Liste**
git diff DCLP/61/60254.xml

**ohne @n**
git diff DCLP/61/60822.xml

**mit @n**
Gibt es das überhaupt???

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/c1cf77027fef60b4eab978f75ef53656523a18a7

**Comment by jcowey** [comment]
Looks great. I have tested random ones and looked at them in DCLP. It is all fine.

**Comment by Edelweiss** [comment]
biblScope attribute must be ```@unit``` instead of ```@type```

```xml
<biblScope type="number">214</biblScope>
```
```xml
<biblScope type="unit">214</biblScope>
```

See…

https://travis-ci.org/papyri/idp.data/jobs/611251797

**Comment by Edelweiss** [comment]
https://github.com/papyri/idp.data/commit/73b48d05438f5c853fc0e822dbc6203ed62d4a7b
